# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Treat slashes as word separators so navigation and editing commands (e.g., Ctrl+W) stop at directory boundaries
WORDCHARS=${WORDCHARS/\/}

# Use Emacs-style keybindings
bindkey -e

# Disable terminal bell on errors
unsetopt beep

# Enable extended globbing (e.g., ^, ~, # in patterns)
setopt extendedglob

# --- History ---
HISTFILE=~/.histfile
HISTSIZE=1000000       # Max entries kept in memory
SAVEHIST=1000000       # Max entries written to HISTFILE
setopt histignorealldups   # Deduplicate history, keeping only the latest occurrence
setopt histreduceblanks    # Remove superfluous leading spaces in recorded commands
setopt inc_append_history  # Write each command to HISTFILE immediately (safe for multiple terminals)

# --- Completion ---
zstyle :compinstall filename "$HOME/.zshrc"
# Highlight the currently selected item when cycling through completion options with Tab
zstyle ':completion:*' menu select

autoload -Uz compinit
# Rebuild completion dump only once a day; otherwise reuse the cached dump
if [[ -n ~/.zcompdump(#qN.mh+24) ]]; then
  compinit
else
  compinit -C
fi

# --- Aliases ---
alias sudo='sudo '
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'
alias ls='ls --color=auto'
alias ll='ls -lh'
alias rsync='rsync -P'
alias sudovim=sudoedit
cmd_exists nvim && alias vim=nvim

# --- Plugins (loaded after compinit) ---
() {
  local plugin_dirs=(
    ~/.local/share
    /usr/share
    /usr/share/zsh/plugins # For Arch Linux
  )
  local dir
  function load_plugin {
    for dir in $plugin_dirs; do if [[ -f $dir/$1 ]]; then
      source $dir/$1; break
    fi; done
  }
  load_plugin zsh-autosuggestions/zsh-autosuggestions.zsh
  load_plugin zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  load_plugin zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
}

# Load Powerlevel10k theme configuration (generated by `p10k configure`)
source ~/.p10k.zsh

# Source machine-local zshrc overrides if present
[[ -f ~/.zshrcl ]] && source ~/.zshrcl
