export EDITOR=nvim
export PATH=~/.local/bin:~/.cargo/bin:$PATH
export GOPATH=~/.local/lib/go
export proxy=http://127.0.0.1:10800
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
