# alias {{{
alias sudo='sudo '
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'
alias p='proxychains -q '
alias setp="export http_proxy=$proxy https_proxy=$proxy"
alias unsetp='unset http_proxy https_proxy'
alias ls='ls --color=auto'
alias ll='ls -lh'
alias winecn='LC_ALL=zh_CN.UTF-8 wine'
alias winejp='LC_ALL=ja_JP.UTF-8 wine'
alias update-grub='grub-mkconfig -o /boot/grub/grub.cfg'
alias cnpm='npm --registry https://registry.npm.taobao.org'
# }}}

# source {{{
eval "$(fasd --init auto)"
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
source /usr/share/doc/pkgfile/command-not-found.zsh
source /etc/zsh/p10k.zsh
# }}}

# zsh-newuser-install
HISTSIZE=100000000
SAVEHIST=$HISTSIZE
HISTFILE=~/.histfile
unsetopt beep
bindkey -e

# compinstall
zstyle :compinstall filename ~/.zshrc
autoload -Uz compinit
compinit

zstyle ':completion:*' menu select
WORDCHARS=${WORDCHARS/\/}
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
setopt -o sharehistory
tabs 4

[[ ! -f /etc/zsh/zshrcl ]] || source /etc/zsh/zshrcl
